version: "3.8"
services:
  logger-app:
    container_name: logger-app
    image: logger-app
    restart: always
    build: .
    ports:
      - 8081:8081
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - /Users/kolyacheranmac/Desktop/volumes:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test_results
      MYSQL_ROOT_PASSWORD: root